/*
Auto-generated by TFLiteTraining export.
*/

#ifndef TFLITE_MODEL_SETTINGS_H_
#define TFLITE_MODEL_SETTINGS_H_

#include <stdint.h>
#include "image_provider.h"

// Derived from image_provider.h — change OUT_WIDTH/OUT_HEIGHT there.
constexpr int kNumCols = OUT_WIDTH;
constexpr int kNumRows = OUT_HEIGHT;
constexpr int kNumChannels = 1;

constexpr int kMaxImageSize = kNumCols * kNumRows * kNumChannels;

constexpr int kCategoryCount = 4;
extern const char* kCategoryLabels[kCategoryCount];
extern const uint8_t kClassTypes[kCategoryCount];  // 0=sign, 1=road

#endif  // TFLITE_MODEL_SETTINGS_H_
