/*
Auto-generated by TFLiteTraining export.
*/

#include "model_settings.h"

const char* kCategoryLabels[kCategoryCount] = {
    "CROSS", "END", "NOENTRY", "straghtline",
};

const uint8_t kClassTypes[kCategoryCount] = {
    1, 0, 0, 1,
};
