/*
Auto-generated by TFLiteTraining export.
*/

#ifndef TFLITE_MODEL_SETTINGS_H_
#define TFLITE_MODEL_SETTINGS_H_

constexpr int kNumCols = 96;
constexpr int kNumRows = 96;
constexpr int kNumChannels = 1;

constexpr int kMaxImageSize = kNumCols * kNumRows * kNumChannels;

constexpr int kCategoryCount = 3;
extern const char* kCategoryLabels[kCategoryCount];

#endif  // TFLITE_MODEL_SETTINGS_H_
